kind: pipeline
type: docker
name: Publish to server

volumes:
- name: webroot
  host:
    path: /var/www/www.hunterwittenborn.com/

steps:
- name: Push code to directory
  image: ubuntu
  volumes:
  - name: webroot
    path: /var/www/www.hunterwittenborn.com/
  commands:
    - rm /var/www/www.hunterwittenborn.com/* -R || printf ""
    - cp -r  * /var/www/www.hunterwittenborn.com/
